#
# Executes commands at login post-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code that does not affect the current session in the background.
{
  [[ $+commands[compile-completions] ]] && compile-completions

  [[ "$OSTYPE" == darwin* ]] && [[ $+commands[update-system-env] ]] && update-system-env
} &!

if [[ "$PROFILE_STARTUP" == true ]]; then
  zprof
  unsetopt xtrace
  exec 2>&3 3>&-
fi

# vim:ft=zsh
