#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ -z "$BROWSER" && "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

if [[ -z "$EDITOR" ]]; then
  export EDITOR='vim -X'
fi
if [[ -z "$VISUAL" ]]; then
  export VISUAL='vim -X'
fi
if [[ -z "$PAGER" ]]; then
  export PAGER='less'
fi

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  ./bin
  $HOME/{,s}bin(N)
  $HOME/{.local/bin,.iterm2}
  /opt/{homebrew,local}/{,s}bin(N)
  /usr/local/{,s}bin(N)
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X to enable it.
#if [[ -z "$LESS" ]]; then
  export LESS='-g -i -M -R -S -w -X -z-4'
#fi

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if [[ -z "$LESSOPEN" ]] && (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

# Locales
export LANG="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_MONETARY="pt_BR.UTF-8"
export LC_NUMERIC="pt_BR.UTF-8"
export LC_TIME="pt_BR.UTF-8"
export LC_ALL=

[[ -d /usr/local/share/zsh/site-functions ]] && site_functions_path=/usr/local/share/zsh/site-functions

# Gradle
[[ -d /usr/local/opt/gradle ]] && export GRADLE_HOME=/usr/local/opt/gradle/libexec

# Groovy
[[ -d /usr/local/opt/groovy/libexec ]] && export GROOVY_HOME=/usr/local/opt/groovy/libexec

# Liquibase
[[ -d /usr/local/opt/liquibase/libexec ]] && export LIQUIBASE_HOME=/usr/local/opt/liquibase/libexec

# Hadoop
[[ -d /usr/local/opt/hadoop/libexec ]] && export HADOOP_HOME=/usr/local/opt/hadoop/libexec

# Spark
[[ -d /usr/local/opt/apache-spark/libexec ]] && export SPARK_HOME=/usr/local/opt/apache-spark/libexec
export PYSPARK_PYTHON=python3

# Android SDK path
[[ -d /usr/local/opt/android-sdk ]] && export ANDROID_HOME=/usr/local/opt/android-sdk

# FindBugs
[[ -d /usr/local/opt/findbugs ]] && export FINDBUGS_HOME=/usr/local/opt/findbugs

# nvm
[[ -d "$HOME/.nvm" ]] && export NVM_DIR="$HOME/.nvm"

# rbenv
if [[ -d "$HOME/.rbenv" ]]; then
  export RBENV_ROOT=$HOME/.rbenv
elif [[ "$OSTYPE" == darwin* ]]; then
  export RBENV_ROOT=/usr/local/var/rbenv
fi

# bat
export BAT_THEME='TwoDark'

# pyenv
[[ -d /usr/local/var/pyenv ]] && export PYENV_ROOT=/usr/local/var/pyenv
[[ -d "$HOME/.pyenv" ]] && export PYENV_ROOT="$HOME/.pyenv"

# Heroku Client
[[ -d /usr/local/heroku/bin ]] && export PATH="/usr/local/heroku/bin:$PATH"

# Docker Rootless mode
[[ -S "$XDG_RUNTIME_DIR/docker.sock" ]] && export DOCKER_HOST="unix://$XDG_RUNTIME_DIR/docker.sock"

# Go environment
if [[ -d "$HOME/workspace/go" ]]; then
  export GOPATH="$HOME/workspace/go"
  export PATH="$PATH:$GOPATH/bin"
fi

[[ -d ~/.emacs.d/bin ]] && path+=(~/.emacs.d/bin)

# Use Python 3 in Google Cloud cli
export CLOUDSDK_PYTHON=python3

export ARCHWAY_SKIP_VERSION_CHECK=true
